import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  // src/lib/api-schema.d.ts is generated by `npm run generate:api`; don't lint it.
  { ignores: ["dist", "coverage", "node_modules", "src/lib/api-schema.d.ts"] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2022,
      globals: { ...globals.browser, ...globals.node },
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
    },
  },
  {
    // shadcn-style primitives export their variant helpers; providers export their hooks.
    files: ["src/components/ui/**/*.tsx", "src/lib/**/*.tsx"],
    rules: { "react-refresh/only-export-components": "off" },
  },
);
