/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/chunks/{chunk_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document Chunk Route */
        get: operations["get_document_chunk_route_api_documents__document_id__chunks__chunk_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Project */
        patch: operations["update_project_api_projects__project_id__patch"];
        trace?: never;
    };
    "/api/projects/{project_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_projects__project_id__documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/documents/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Project Documents */
        post: operations["ingest_project_documents_api_projects__project_id__documents_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Project */
        post: operations["search_project_api_projects__project_id__search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workflows */
        get: operations["list_workflows_api_projects__project_id__workflows_get"];
        put?: never;
        /** Create Workflow */
        post: operations["create_workflow_api_projects__project_id__workflows_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/provider-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider Status */
        get: operations["provider_status_api_provider_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tools */
        get: operations["list_tools_api_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow-step-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workflow Step Types */
        get: operations["list_workflow_step_types_api_workflow_step_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow-versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Version */
        get: operations["get_version_api_workflow_versions__version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Version */
        patch: operations["update_version_api_workflow_versions__version_id__patch"];
        trace?: never;
    };
    "/api/workflow-versions/{version_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Version */
        post: operations["approve_version_api_workflow_versions__version_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow-versions/{version_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Version */
        post: operations["restore_version_api_workflow_versions__version_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow-versions/{version_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Version */
        post: operations["validate_version_api_workflow_versions__version_id__validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{workflow_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workflow */
        get: operations["get_workflow_api_workflows__workflow_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{workflow_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Version */
        post: operations["create_version_api_workflows__workflow_id__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CheckData */
        CheckData: {
            /** Detail */
            detail?: string | null;
            /** Latency Ms */
            latency_ms: number;
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error" | "unavailable";
        };
        /** ChunkOut */
        ChunkOut: {
            /** Chunk Id */
            chunk_id: string;
            /** Document External Id */
            document_external_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** End Offset */
            end_offset: number;
            /** Heading */
            heading: string | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Sequence */
            sequence: number;
            /** Start Offset */
            start_offset: number;
            /** Text */
            text: string;
            /** Token Count */
            token_count: number;
        };
        /**
         * ChunkSummary
         * @description A chunk's identity plus a preview, never its full text.
         *
         *     ``preview`` is truncated to ``DOCUMENT_CHUNK_PREVIEW_LENGTH`` characters;
         *     the full text is only ever returned by the single-chunk endpoint.
         */
        ChunkSummary: {
            /** Chunk Id */
            chunk_id: string;
            /** Heading */
            heading: string | null;
            /** Preview */
            preview: string;
            /** Sequence */
            sequence: number;
            /** Token Count */
            token_count: number;
        };
        /** DocumentDetail */
        DocumentDetail: {
            /** Access Group */
            access_group: string;
            /** Chunk Count */
            chunk_count: number;
            /** Chunks */
            chunks: components["schemas"]["ChunkSummary"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Dataset Version */
            dataset_version: string;
            /** Document Type */
            document_type: string;
            /** Effective Date */
            effective_date: string | null;
            /** Expires At */
            expires_at: string | null;
            /** External Id */
            external_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Vendor */
            vendor: string | null;
        };
        /** DocumentList */
        DocumentList: {
            /** Items */
            items: components["schemas"]["DocumentOut"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** DocumentOut */
        DocumentOut: {
            /** Access Group */
            access_group: string;
            /** Chunk Count */
            chunk_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Dataset Version */
            dataset_version: string;
            /** Document Type */
            document_type: string;
            /** Effective Date */
            effective_date: string | null;
            /** Expires At */
            expires_at: string | null;
            /** External Id */
            external_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Vendor */
            vendor: string | null;
        };
        /** Envelope[ChunkOut] */
        Envelope_ChunkOut_: {
            data?: components["schemas"]["ChunkOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Request Id */
            request_id: string;
        };
        /** Envelope[DocumentDetail] */
        Envelope_DocumentDetail_: {
            data?: components["schemas"]["DocumentDetail"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Request Id */
            request_id: string;
        };
        /** Envelope[DocumentList] */
        Envelope_DocumentList_: {
            data?: components["schemas"]["DocumentList"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Request Id */
            request_id: string;
        };
        /** Envelope[HealthData] */
        Envelope_HealthData_: {
            data?: components["schemas"]["HealthData"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Request Id */
            request_id: string;
        };
        /** Envelope[IngestAccepted] */
        Envelope_IngestAccepted_: {
            data?: components["schemas"]["IngestAccepted"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Request Id */
            request_id: string;
        };
        /** Envelope[JobStatusOut] */
        Envelope_JobStatusOut_: {
            data?: components["schemas"]["JobStatusOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Request Id */
            request_id: string;
        };
        /** Envelope[MeOut] */
        Envelope_MeOut_: {
            data?: components["schemas"]["MeOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Request Id */
            request_id: string;
        };
        /** Envelope[ProjectList] */
        Envelope_ProjectList_: {
            data?: components["schemas"]["ProjectList"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Request Id */
            request_id: string;
        };
        /** Envelope[ProjectOut] */
        Envelope_ProjectOut_: {
            data?: components["schemas"]["ProjectOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Request Id */
            request_id: string;
        };
        /** Envelope[ProviderStatus] */
        Envelope_ProviderStatus_: {
            data?: components["schemas"]["ProviderStatus"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Request Id */
            request_id: string;
        };
        /** Envelope[ReadinessData] */
        Envelope_ReadinessData_: {
            data?: components["schemas"]["ReadinessData"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Request Id */
            request_id: string;
        };
        /** Envelope[SearchResult] */
        Envelope_SearchResult_: {
            data?: components["schemas"]["SearchResult"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Request Id */
            request_id: string;
        };
        /** Envelope[StepTypeList] */
        Envelope_StepTypeList_: {
            data?: components["schemas"]["StepTypeList"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Request Id */
            request_id: string;
        };
        /** Envelope[ToolList] */
        Envelope_ToolList_: {
            data?: components["schemas"]["ToolList"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Request Id */
            request_id: string;
        };
        /** Envelope[VersionOut] */
        Envelope_VersionOut_: {
            data?: components["schemas"]["VersionOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Request Id */
            request_id: string;
        };
        /** Envelope[WorkflowDetail] */
        Envelope_WorkflowDetail_: {
            data?: components["schemas"]["WorkflowDetail"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Request Id */
            request_id: string;
        };
        /** Envelope[WorkflowList] */
        Envelope_WorkflowList_: {
            data?: components["schemas"]["WorkflowList"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Request Id */
            request_id: string;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Details */
            details?: unknown[] | {
                [key: string]: unknown;
            } | null;
            /** Message */
            message: string;
        };
        /**
         * EvidenceChunk
         * @description A retrievable passage with the identifiers needed for citations.
         */
        EvidenceChunk: {
            /** Chunk Id */
            chunk_id: string;
            /** Document Id */
            document_id: string;
            /** Document Name */
            document_name: string;
            /** Document Type */
            document_type: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Score */
            score?: number | null;
            /** Text */
            text: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthData */
        HealthData: {
            /** App Env */
            app_env: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** IngestAccepted */
        IngestAccepted: {
            /** Job Id */
            job_id: string;
        };
        /** IngestRequest */
        IngestRequest: {
            /**
             * Dataset Version
             * @default v1
             */
            dataset_version: string;
        };
        /** JobStatusOut */
        JobStatusOut: {
            /** Error */
            error?: string | null;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "deferred" | "in_progress" | "complete" | "failed" | "not_found";
        };
        /** LastError */
        LastError: {
            /** At */
            at: string;
            /** Category */
            category: string;
            /** Code */
            code: string;
        };
        /** MeOut */
        MeOut: {
            /** Access Groups */
            access_groups: string[];
            /** Display Name */
            display_name: string | null;
            /** Email */
            email: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Subject */
            subject: string;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Name */
            name: string;
            /**
             * Vertical
             * @default contract_review
             */
            vertical: string;
        };
        /** ProjectList */
        ProjectList: {
            /** Items */
            items: components["schemas"]["ProjectOut"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** ProjectOut */
        ProjectOut: {
            /** Archived At */
            archived_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Vertical */
            vertical: string;
        };
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Description */
            description?: string | null;
            /** Name */
            name?: string | null;
        };
        /** ProviderStatus */
        ProviderStatus: {
            /** Base Url Host */
            base_url_host: string | null;
            /** Cache Enabled */
            cache_enabled: boolean;
            /** Catalog Version */
            catalog_version: string;
            /** Configured */
            configured: boolean;
            /** Provider */
            provider: string;
            /** Roles */
            roles: components["schemas"]["RoleStatus"][];
        };
        /** ReadinessData */
        ReadinessData: {
            /** Checks */
            checks: components["schemas"]["CheckData"][];
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "degraded" | "not_ready";
        };
        /** RoleStatus */
        RoleStatus: {
            /** Circuit State */
            circuit_state: ("closed" | "open" | "half_open") | null;
            /** Context Window */
            context_window: number | null;
            /** Enabled */
            enabled: boolean;
            /** Fallbacks */
            fallbacks: string[];
            last_error: components["schemas"]["LastError"] | null;
            /** Model */
            model: string | null;
            /** Provider */
            provider: string | null;
            /**
             * Role
             * @enum {string}
             */
            role: "planner" | "extractor" | "drafter" | "evaluator" | "embedding" | "reranker";
            /** Structured Output Mode */
            structured_output_mode: string | null;
            /** Supports Structured Output */
            supports_structured_output: boolean | null;
            /** Supports Tools */
            supports_tools: boolean | null;
        };
        /** SearchRequest */
        SearchRequest: {
            /** Document Types */
            document_types?: string[];
            /**
             * Limit
             * @default 8
             */
            limit: number;
            /** Query */
            query: string;
            /** Vendor */
            vendor?: string | null;
        };
        /** SearchResult */
        SearchResult: {
            /** Chunks */
            chunks: components["schemas"]["EvidenceChunk"][];
            /** Reason */
            reason: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "insufficient_evidence" | "conflicting_evidence";
            /** Total Candidates */
            total_candidates: number;
        };
        /**
         * StepTypeInfo
         * @description A catalog entry describing one step type.
         */
        StepTypeInfo: {
            /** Allowed Tool Kinds */
            allowed_tool_kinds: string[];
            /** Config Schema */
            config_schema: {
                [key: string]: unknown;
            };
            /** Description */
            description: string;
            /** Is Model Driven */
            is_model_driven: boolean;
            /** Output Schema */
            output_schema: {
                [key: string]: unknown;
            };
            /** Title */
            title: string;
            /**
             * Type
             * @enum {string}
             */
            type: "retrieve_documents" | "extract_fields" | "compare_policy" | "classify" | "draft_summary" | "human_review" | "validate_output" | "finish";
        };
        /** StepTypeList */
        StepTypeList: {
            /** Items */
            items: components["schemas"]["StepTypeInfo"][];
        };
        /**
         * ToolInfo
         * @description Catalog-safe description of one registered tool: no implementation details.
         */
        ToolInfo: {
            /**
             * Access Scope
             * @enum {string}
             */
            access_scope: "project_documents" | "policy_library";
            /** Description */
            description: string;
            /** Input Schema */
            input_schema: {
                [key: string]: unknown;
            };
            /**
             * Kind
             * @enum {string}
             */
            kind: "retrieval" | "lookup";
            /** Name */
            name: string;
            /** Output Schema */
            output_schema: {
                [key: string]: unknown;
            };
            /**
             * Side Effect Class
             * @enum {string}
             */
            side_effect_class: "read_only" | "draft_only";
        };
        /** ToolList */
        ToolList: {
            /** Items */
            items: components["schemas"]["ToolInfo"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VersionCreate */
        VersionCreate: {
            /** Definition */
            definition: {
                [key: string]: unknown;
            };
            /** Source Request */
            source_request?: string | null;
        };
        /** VersionOut */
        VersionOut: {
            /** Approved At */
            approved_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Definition */
            definition: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source Request */
            source_request?: string | null;
            /** Status */
            status: string;
            /** Validation Warnings */
            validation_warnings: string[];
            /** Version Number */
            version_number: number;
            /**
             * Workflow Id
             * Format: uuid
             */
            workflow_id: string;
        };
        /** VersionSummary */
        VersionSummary: {
            /** Approved At */
            approved_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Version Number */
            version_number: number;
        };
        /** VersionUpdate */
        VersionUpdate: {
            /** Definition */
            definition: {
                [key: string]: unknown;
            };
        };
        /** WorkflowCreate */
        WorkflowCreate: {
            /** Definition */
            definition: {
                [key: string]: unknown;
            };
            /**
             * Description
             * @default
             */
            description: string;
            /** Name */
            name: string;
        };
        /** WorkflowDetail */
        WorkflowDetail: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Version Id */
            current_version_id?: string | null;
            /** Description */
            description: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Versions */
            versions: components["schemas"]["VersionSummary"][];
        };
        /** WorkflowList */
        WorkflowList: {
            /** Items */
            items: components["schemas"]["WorkflowSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** WorkflowSummary */
        WorkflowSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Version Number */
            current_version_number?: number | null;
            /** Current Version Status */
            current_version_status?: string | null;
            /** Description */
            description: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_document_api_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_DocumentDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_chunk_route_api_documents__document_id__chunks__chunk_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
                chunk_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ChunkOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_JobStatusOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_MeOut_"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProjectList_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProjectOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProjectOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProjectOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_projects__project_id__documents_get: {
        parameters: {
            query?: {
                document_type?: string | null;
                vendor?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_DocumentList_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_project_documents_api_projects__project_id__documents_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_IngestAccepted_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_project_api_projects__project_id__search_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SearchResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workflows_api_projects__project_id__workflows_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_WorkflowList_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_workflow_api_projects__project_id__workflows_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_WorkflowDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provider_status_api_provider_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProviderStatus_"];
                };
            };
        };
    };
    list_tools_api_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ToolList_"];
                };
            };
        };
    };
    list_workflow_step_types_api_workflow_step_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_StepTypeList_"];
                };
            };
        };
    };
    get_version_api_workflow_versions__version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_VersionOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_version_api_workflow_versions__version_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_VersionOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_version_api_workflow_versions__version_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_VersionOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_version_api_workflow_versions__version_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_VersionOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_version_api_workflow_versions__version_id__validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_VersionOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workflow_api_workflows__workflow_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_WorkflowDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_version_api_workflows__workflow_id__versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_VersionOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_HealthData_"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ReadinessData_"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ReadinessData_"];
                };
            };
        };
    };
}
